CTF-Learning-Website/urls.py
from CTF_App.views_api import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'articles', ArticleViewSet)
router.register(r'sections', SectionViewSet, basename='section')
router.register(r'comments', CommentViewSet)
router.register(r'tests', TestViewSet)
router.register(r'questions', QuestionViewSet)
router.register(r'questions-in-test', QuestionInTestViewSet)
router.register(r'answers', AnswerViewSet)
router.register(r'custom-users', CustomUserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("debug/", include("debug_toolbar.urls")),
    path("", include("CTF_App.urls")),
    path("api/", include(router.urls)),
    path('api/auth/register/', RegisterView.as_view(), name='register'),
    path('api/auth/login/', LoginView.as_view(), name='login'),
    path('api/create-module/', CreatemoduleView.as_view(), name='create-module'),
    path('api/auth/update-email/', EmailUpdateView.as_view(), name='update-email'),
    path('api/auth/change-password/', PasswordChangeView.as_view(), name='change-password'),
    path('api/tests/<int:test_id>/', TestDetailView.as_view(), name='test-detail'),
    path('api/auth/logout/', LogoutView.as_view(), name='logout'),
    path('api/update_score/', update_score, name='update_score'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CTF_App/urls.py
from django.urls import path, include

from . import views

app_name = 'CTF_App'

urlpatterns = [

    # URL pattern cho trang chủ
    path('', views.IndexView.as_view(), name='index'),

    # URL pattern cho trang chi tiết bài viết
    path('articles/<uuid:pk>/', views.DetailView.as_view(), name='article_detail'),

    # URL pattern cho trang xếp hạng
    path('scoreboard/', views.ScoreboardView.as_view(), name='scoreboard'),

    # URL pattern cho trang đăng nhập
    path('login/', views.user_login, name='login'),

    # URL pattern cho trang đăng xuất
    path('logout/', views.user_logout, name='logout'),

    # URL pattern cho trang đăng ký
    path('signup/', views.user_signup, name='signup'),

    # URL pattern cho trang profile
    path('profile/', views.profile_view, name='profile'),

    # URL pattern cho trang change_username
    path('change_username/', views.change_username, name='change_username'),

    # URL pattern cho trang change_email
    path('change_email/', views.change_email, name='change_email'),

    # URL pattern cho trang change_password
    path('change_password/', views.change_password, name='change_password'),

    # URL pattern cho trang tạo bài viết
    path('articles/create/', views.ArticleCreateView.as_view(), name='article_create'),

    # URL pattern xóa bài viết
    path('articles/<uuid:article_id>/delete/', views.delete_article, name='delete_article'),

    # URL pattern cho trang thêm section
    path('articles/<uuid:article_id>/add_section/', views.add_section, name='add_section'),

    # URL pattern cho trang chỉnh sửa bài viết
    path('section/edit/<uuid:section_id>/', views.edit_section, name='edit_section'),
    path('section/delete/<uuid:section_id>/', views.delete_section, name='delete_section'),
    path('article/<uuid:article_id>/add_section/', views.add_section, name='add_section'),
    path('article/<uuid:article_id>/add_section/<int:position>/', views.add_section, name='add_section'),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # URL pattern cho trang làm bài test
    path('article/<uuid:article_id>/test/', views.take_test, name='take_test'),
    path('article/<uuid:article_id>/edit_test/', views.edit_test, name='edit_test'),
    path('article/<uuid:article_id>/add_test/', views.add_test, name='add_test'),

    # URL pattern cho trang chỉnh sửa avatar
    path('change_avatar/', views.change_avatar, name='change_avatar'),
]

CTF_App/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
import bleach


class Test(models.Model):
    models.AutoField(primary_key=True)
    difficulty = models.CharField(max_length=50)


class Articles(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255, default='')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='articles', default='')
    date = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=50)
    test = models.ForeignKey(Test, on_delete=models.SET_NULL, null=True, blank=True)
    total_views = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Sections(models.Model):
    ARTICLE_PART_TYPES = [
        ('text', 'Text'),
        ('image', 'Image'),
        ('video', 'Video'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    article = models.ForeignKey(Articles, on_delete=models.CASCADE, related_name='sections')
    part_type = models.CharField(max_length=10, choices=ARTICLE_PART_TYPES)
    text = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='article_images/', null=True, blank=True)
    video_url = models.URLField(max_length=200, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    position = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.article.name} - {self.part_type} - {self.position}"

    def save(self, *args, **kwargs):
        if self.text:
            self.text = bleach.clean(self.text, tags=['b', 'i', 'u', 'em', 'strong', 'a', 'ul', 'ol', 'li', 'br'],
                                     attributes={'a': ['href']})
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['position']


class AuthorOfArticle(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    article = models.ForeignKey(Articles, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default='')


class Question(models.Model):
    id = models.AutoField(primary_key=True)
    content = models.TextField()

    def __str__(self):
        return self.content


class QuestionInTest(models.Model):
    id = models.AutoField(primary_key=True)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)


class Answer(models.Model):
    id = models.AutoField(primary_key=True)
    content = models.TextField()
    result = models.BooleanField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE, default='')


class CustomUser(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    score = models.FloatField(default=0)
    contribution = models.IntegerField(default=0)
    rank = models.IntegerField(default=0)
    avatar = models.ImageField(upload_to='avatar_images/', null=True, blank=True)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Articles, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

CTF_App/views.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.core import serializers
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import F
from django.forms import inlineformset_factory, modelformset_factory, Textarea
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from rest_framework import generics, permissions, serializers, status, viewsets
from rest_framework.response import Response

from .models import *


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class IndexView(generic.ListView):
    template_name = "CTF_App/index.html"
    context_object_name = "latest_article_list"
    model = Articles
    paginate_by = 5

    def get_queryset(self):
        category = self.request.GET.get('category')
        search_query = self.request.GET.get('search')

        queryset = Articles.objects.all()

        if category:
            queryset = queryset.filter(category=category)

        if search_query:
            queryset = queryset.filter(name__icontains=search_query)

        return queryset.order_by('-date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_query = self.request.GET.get('search', '')

        # Pagination
        queryset = self.get_queryset()
        paginator = Paginator(queryset, self.paginate_by)
        page = self.request.GET.get('page')

        try:
            articles = paginator.page(page)
        except PageNotAnInteger:
            articles = paginator.page(1)
        except EmptyPage:
            articles = paginator.page(paginator.num_pages)

        context['latest_article_list'] = articles
        context['search_query'] = search_query
        context['page_obj'] = articles

        return context


class DetailView(generic.DetailView):
    template_name = "CTF_App/article_detail.html"
    model = Articles
    context_object_name = "article"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sections'] = self.object.sections.order_by('position')
        context['avatar'] = self.object.author.customuser.avatar.url
        context['comments'] = Comment.objects.filter(article=self.object)
        context['comment_form'] = CommentForm()
        return context

    def get_object(self, queryset=None):
        if not hasattr(self, '_article'):
            self._article = super().get_object(queryset)
            self._article.total_views += 1
            self._article.save()
        return self._article

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.article = self.get_object()
            comment.save()
            messages.info(request, "Your comment has been recorded!")
        return redirect('CTF_App:article_detail', pk=self.get_object().pk)


class ScoreboardView(generic.ListView):
    template_name = 'CTF_App/scoreboard.html'
    context_object_name = 'users'
    model = User

    def get_queryset(self):
        return User.objects.annotate(
            score=F('customuser__score'),
            contribution=F('customuser__contribution')
        ).order_by('-score', '-contribution')


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return redirect('CTF_App:index')
        else:
            # Return an 'invalid login' error message.
            messages.error(request, 'Invalid username or password. Please try again.')
            return render(request, "CTF_App/login.html")
    else:
        return render(request, 'CTF_App/login.html')


def user_logout(request):
    logout(request)
    # Redirect to a success page.
    return redirect('CTF_App:index')


def user_signup(request):
    if request.method == 'POST':
        # Lấy dữ liệu từ form đăng ký
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')

        # Kiểm tra nếu đã có user với username hoặc email đã nhập
        if User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists():
            # Nếu đã tồn tại user với username hoặc email đã nhập, thông báo lỗi
            messages.error(request, 'Username or email already exists.')
            return render(request, 'CTF_App/signup.html')

        # Kiểm tra mật khẩu có đủ mạnh không
        try:
            validate_password(password)
        except ValidationError as e:
            messages.error(request, e)
            return render(request, 'CTF_App/signup.html')

        # Tạo một user mới
        user = User.objects.create_user(username=username, password=password, email=email)

        # Lưu user mới vào cơ sở dữ liệu
        user.save()

        # Tạo một CustomUser mới tương ứng với user mới
        custom_user = CustomUser.objects.create(
            user=user,
            score=0,
            contribution=0,
            rank=0,
            avatar='default.jpg'
        )

        # Lưu CustomUser mới vào cơ sở dữ liệu
        custom_user.save()

        # authenticate và login giúp đăng nhập người dùng sau khi họ đăng ký
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)

        # Chuyển hướng người dùng đến trang chủ hoặc trang sau khi đăng ký thành công
        return redirect('CTF_App:index')

    # Nếu không phải là phương thức POST, render template cho trang đăng ký
    return render(request, 'CTF_App/signup.html')


@login_required
def profile_view(request):
    current_user = request.user
    ordered_users_list = CustomUser.objects.order_by('-score', '-contribution')
    rank = list(ordered_users_list).index(current_user.customuser) + 1
    context = {
        'user': current_user,
        'avatar': CustomUser.objects.get(user=current_user).avatar.url,
        'score': CustomUser.objects.get(user=current_user).score,
        'contribution': CustomUser.objects.get(user=current_user).contribution,
        'rank': rank,
    }
    return render(request, 'CTF_App/profile.html', context)


@login_required
def change_avatar(request):
    if request.method == 'POST':
        avatar = request.FILES['avatar']
        custom_user = CustomUser.objects.get(user=request.user)
        custom_user.avatar.delete()
        custom_user.avatar = avatar
        custom_user.save()
        return redirect('CTF_App:profile')
    return render(request, 'CTF_App/change_avatar.html')


class ChangeUsernameForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']


class ChangeEmailForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'size': '50'}))

    class Meta:
        model = User
        fields = ['email']


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput, label='Old Password')
    new_password = forms.CharField(widget=forms.PasswordInput, label='New Password')
    confirm_password = forms.CharField(widget=forms.PasswordInput, label='Confirm New Password')

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")

        if new_password != confirm_password:
            raise forms.ValidationError("New password and confirm password do not match.")


@login_required
def change_username(request):
    if request.method == 'POST':
        form = ChangeUsernameForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your username was successfully updated!')
            return redirect('CTF_App:profile')
    else:
        form = ChangeUsernameForm(instance=request.user)
    return render(request, 'CTF_App/change_username.html', {'form': form})


@login_required
def change_email(request):
    if request.method == 'POST':
        form = ChangeEmailForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your email was successfully updated!')
            return redirect('CTF_App:profile')
    else:
        form = ChangeEmailForm(instance=request.user)
    return render(request, 'CTF_App/change_email.html', {'form': form})


@login_required
def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            old_password = form.cleaned_data.get('old_password')
            new_password = form.cleaned_data.get('new_password')
            if request.user.check_password(old_password):
                request.user.set_password(new_password)
                request.user.save()
                update_session_auth_hash(request, request.user)  # Important!

CTF_App/templates/CTF_App/add_section.html
{% extends "CTF_App/base.html" %}

{% block extra_css %}
<style>
    textarea {
        resize: vertical;
        width: 770px;
        height: 500px;
        color: white;
        background: #121212;
    }

    .content img, .content video {
        max-width: 100%;
        height: auto;
    }

    .content pre {
        white-space: pre-wrap; /* Giữ lại khoảng trắng và xuống dòng */
    }
</style>
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card bg-dark text-light">
                <div class="card-header">
                    <h3>Add Section to {{ article.name }}</h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Add Section</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CTF_App/templates/CTF_App/add_test.html
{% extends "CTF_App/base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <div class="text-center">{{ message }}</div>
            {% endfor %}
        </ul>
        {% endif %}
        <div class="col-md-8 offset-md-2">
            <div class="card bg-dark text-light">
                <div class="card-header">
                    <h2>Add Test to {{ article.name }}</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="difficulty">Test Difficulty</label>
                            <input type="text" class="form-control" id="difficulty" name="difficulty" required>
                        </div>
                        <br><br>
                        <button type="submit" class="btn btn-primary">Add Test</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CTF_App/templates/CTF_App/article_detail.html
{% extends "CTF_App/base.html" %}

{% block extra_css %}
<style>
    .article-header {
        text-align: center;
        margin-bottom: 20px;
        color: goldenrod;
    }

    .content img, .content video {
        max-width: 100%;
        height: auto;
    }

    .content pre {
        white-space: pre-wrap; /* Giữ lại khoảng trắng và xuống dòng */
    }

    .btn-group {
        margin-top: 20px;
        display: flex;
        justify-content: center;
        gap: 10px;
    }

    .comment-form textarea {
        width: 100%;
        height: 100px;
        margin-bottom: 10px;
    }
</style>
{% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div style="align-self: center; justify-content: center; align-items: center;">
            {% if messages %}
            <ul class="messages" style="align-self: center; justify-content: center; align-items: center; width: 60%; margin-left: 225px">
                {% for message in messages %}
                <div class="alert alert-warning text-center" role="alert"
                     style="align-self: center; justify-content: center; align-items: center; font-size: large">
                    {{message}}
                </div>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
        <div class="col-md-8 offset-md-2">
            <div class="card bg-dark text-light">
                <div class="card-header article-header">
                    <h2>{{ article.name }}</h2>
                </div>
                <div class="card-body">
                    <img alt="Author's avatar"
                         src="{{ avatar }}"
                         style="border: 2px solid gold; border-radius: 25px;"
                         width="100">
                    <br>
                    <br>
                    <p class="mb-4"><strong class="text-info">Author:</strong> {{ article.author }}</p>
                    <p class="mb-4"><strong class="text-info">Date:</strong> {{ article.date }}</p>
                    <hr class="bg-light mb-4">
                    <div class="content">
                        {% for section in sections %}
                        {% if section.part_type == 'text' %}
                        <pre>{{ section.text|safe }}</pre>
                        {% elif section.part_type == 'image' %}
                        <img alt="Article Image" class="img-fluid mx-auto d-block" width="100%" height="70%" src="{{ section.image.url }}">
                        {% elif section.part_type == 'video' %}
                        <iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                                allowfullscreen frameborder="0"
                                height="315"
                                referrerpolicy="strict-origin-when-cross-origin"
                                src="{{ section.video_url }}"
                                title="YouTube video player"
                                width="100%">
                        </iframe>
                        {% endif %}
                        <br>
                        {% if user.is_authenticated and user == article.author %}
                        <a class="btn btn-warning" href="{% url 'CTF_App:edit_section' section.id %}">Edit</a>
                        <span style="margin-right: 30px;"></span>
                        <a class="btn btn-danger" href="{% url 'CTF_App:delete_section' section.id %}">Delete</a>
                        <span style="margin-right: 30px;"></span>
                        <a class="btn btn-primary" href="{% url 'CTF_App:add_section' article.id section.position %}">Add above</a>
                        <hr>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <div class="btn-group">
                        {% if user.is_authenticated and user == article.author %}
                        <a class="btn btn-primary" href="{% url 'CTF_App:add_section' article.id %}">Add Section</a>
                        {% if article.test %}
                        <a class="btn btn-warning" href="{% url 'CTF_App:edit_test' article.id %}">Edit Test</a>
                        {% else %}
                        <a class="btn btn-primary" href="{% url 'CTF_App:add_test' article.id %}">Add Test</a>
                        {% endif %}
                        <a class="btn btn-danger" href="{% url 'CTF_App:delete_article' article.id %}">Delete Article</a>
                        {% else %}
                        {% if article.test and user.is_authenticated %}
                        <a class="btn btn-primary" href="{% url 'CTF_App:take_test' article.id %}">Start Quiz</a>
                        {% endif %}
                        {% endif %}
                    </div>
                    <hr>
                    <div class="comments">
                        <h3>Comments</h3>
                        {% for comment in comments %}
                        <div class="comment">
                            <p class="text-info">{{ comment.user.username }} ({{ comment.created_at }}) :</p>
                            {{comment.text }}</p>
                        </div>
                        {% endfor %}
                    </div>
                    <hr>
                    <div class="comment-form">
                        <h3>Leave a comment</h3>
                        <form method="post">
                            {% csrf_token %}
                            {{ comment_form.as_p }}
                            {% if user.is_authenticated %}
                            <button class="btn btn-primary" type="submit">
                                Submit
                            </button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script>
    // reload the page and move to the previous position
    window.onload = function () {
        window.scrollTo(0, localStorage.getItem('scrollPosition'));
    }
    window.onbeforeunload = function () {
        localStorage.setItem('scrollPosition', window.scrollY);
    }
</script>
{% endblock %}

CTF_App/templates/CTF_App/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <title>CTF Learning - Home</title>
    <link href="{% static 'static/Media/Logo.jpg' %}" rel="icon">
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
          rel="stylesheet"/>
    <link href="{% static 'static/css/style.css' %}" rel="stylesheet">
    <style>
        body {
            background-color: #121212;
            color: #fff;

            .navbar {
                background-color: #1f1f1f;
            }

            .navbar-brand, .nav-link, .dropdown-item {
                color: #fff !important;
            }

            .navbar-brand:hover, .nav-link:hover, .dropdown-item:hover {
                color: #bbb !important;
            }

            .navbar-toggler {
                border: none;
            }

            .btn {
                margin-right: 10px;
            }

            .container {
                padding-top: 20px;
            }

            .dropdown-menu {
                background-color: #1f1f1f;
            }

            .dropdown-item {
                transition: background-color 0.2s, color 0.2s;
            }

            .dropdown-item:hover {
                background-color: #343a40;
                color: #fff;
            }

            .nav-item {
                margin-left: 10px;
            }

            .categories-section {
                margin-top: 20px;
                padding: 20px;
                background-color: #1f1f1f;
                border-radius: 5px;
            }

            .categories-section h5 {
                margin-bottom: 15px;
            }
        }
    </style>
    {% block extra_css %}{% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'CTF_App:index' %}">
            <img alt="logo" class="d-inline-block align-text-top" height="30" id="logo"
                 src="{% static 'static/Media/Logo.jpg' %}" width="30">
            CTF Learning
        </a>
        <button aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"
                data-bs-target="#navbarTogglerDemo02" data-bs-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a aria-current="page" class="nav-link active" href="{% url 'CTF_App:index' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'CTF_App:article_create' %}">Contribute Article</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'CTF_App:scoreboard' %}">Scoreboard</a>
                </li>
                <li class="nav-item dropdown">
                    <a aria-expanded="false" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"
                       id="navbarDropdown" role="button" style="color: white">
                        Categories
                    </a>
                    <ul aria-labelledby="navbarDropdown" class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'CTF_App:index' %}?category=Web Security">Web
                            Security</a></li>
                        <li><a class="dropdown-item" href="{% url 'CTF_App:index' %}?category=Forensics">Forensics</a>
                        </li>
                        <li><a class="dropdown-item"
                               href="{% url 'CTF_App:index' %}?category=Cryptography">Cryptography</a></li>
                        <li><a class="dropdown-item" href="{% url 'CTF_App:index' %}?category=Binary Exploitation">Binary
                            Exploitation</a></li>
                        <li><a class="dropdown-item" href="{% url 'CTF_App:index' %}?category=Reverse Engineering">Reverse
                            Engineering</a></li>
                        <li><a class="dropdown-item" href="{% url 'CTF_App:index' %}?category=Misc">Misc</a></li>
                    </ul>
                </li>
            </ul>
            <div class="d-flex">
                {% if user.is_authenticated %}
                <a class="btn btn-danger" href="{% url 'CTF_App:logout' %}">Logout</a>
                <span style="margin-right: 30px;"></span>
                <a class="btn btn-primary" href="{% url 'CTF_App:profile' %}">Profile</a>
                {% else %}
                <a class="btn btn-success" href="{% url 'CTF_App:login' %}">Login</a>
                <span style="margin-right: 30px;"></span>
                <a class="btn btn-primary" href="{% url 'CTF_App:signup' %}">Signup</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}

    {% endblock %}

    {% block extra_js %}

    {% endblock %}
</div>
</body>
</html>